version: "3"
services:
  web:
    build: .
    image: dev/vtxok
    ports:
      - 8000:8000
    command: gunicorn -w 4 --proxy-protocol --paste development.ini -b 0.0.0.0:8000
    labels:
      - "traefik.backend=vtxok"
      - "traefik.frontend.rule=Host:vortexok.net, www.vortexok.net"
      - "traefik.enable=true"

networks:
  default:
    external:
      name: dh1proxy_webproxy
